### PR TITLE
Red Hat OpenJDK is not Free.

### PR DESCRIPTION
**Pull request by yamadamn**
You should check Red Hat Enterprise Agreement (EA).
When you download from the site[1], you must agree to the EA and Developer Program Terms & Conditions.

[1] https://developers.redhat.com/products/openjdk/download

### CODE REVIEW

**Comment by raphw** [comment]
You are right about the license for Oracle JDK, I have changed the name.

As for Red Hat's builds: I don't agree here. You need to login to download but the downloads are free and the builds are licensed under GPLv2 without any additional ammendments. You cannot get support for these particular downloads but you are allowed to use them in production whilst this is of course not Red Hat's suggestion. In this sense, the builds are free for any use which is what this column means to express.

**Comment by yamadamn** [comment]
> As for Red Hat's builds: I don't agree here. You need to login to download but the downloads are free and the builds are licensed under GPLv2 without any additional ammendments.

Unfortunately No. We must agree to EA and  Developer Program Terms & Conditions.
image

**Comment by raphw** [comment]
And where do these state that you need to purchase support for production usage?

**Comment by yamadamn** [comment]
If you read the Enterprise Agreement and Developer Program Terms, you can understand.
Basically, products of Red Hat need a subscription.

I quote in part from "Developer Program Click-through Terms".

> By participating in the Program and accepting these terms, you represent that you will be using the Red Hat Subscriptions(s) for development purposes only, and Red Hat is relying on your representation as a condition of our providing you access to the Subscription(s).
> If you use the Red Hat Subscriptions for any other purposes, you are in violation of Red Hat’s Enterprise Agreement set forth below and are required to pay the applicable subscription fees, in addition to any and all other remedies available to Red Hat under applicable law.

**Comment by yamadamn** [comment]
And, you can confirm the following link and comments.
https://access.redhat.com/articles/1299013#OpenJDK_Entitlements
https://access.redhat.com/articles/1299013#comment-1724491

**Comment by kishida** [comment]
@yamadamn Under the GPLv2, execution of the program is not restricted, and even Red Hat they can not impose the additional ristriction.

**Comment by yamadamn** [comment]
@kishida We discuss about "additional ammendments".

**Comment by kishida** [comment]
@yamadamn Where is the additional ammendments for GPLv2?

**Comment by kishida** [comment]
`LICENSE` file in the downloaded archive from "Red Hat Developer", there is a sentence

> The act of running the Program is not restricted

**Pull request closed without merging**
